- name: data types
  hosts: local 
  connection: local
  vars:
   Course: devops with aws #string 
   Duration: 120     #int
   IS_Live: true #boolean
   Tools: #list
   - shell 
   - linux
   Content:
    cicd: jenkins 
    script: "shell,python,terraform,ansible"

  tasks:
  - name: my course information 
  ansible.builtin.debug:
    msg: "{{ Course }} ,{{ Duration }},{{ IS_Live }},{{ Tools }},{{ Content }} "