- name: play with variables
  hosts: local 
  connection: local
  vars:
   Course: devops with aws 
   Institution: joindevops 
   Duration: 120hrs 

  tasks:
  - name: my course information 
  ansible.builtin.debug:
   msg: "i am learning a {{ Course }} from {{ Institution }} durations of {{ Duration }}"
 